spring.application.name=tps-data-producer

# Kafka producer
spring.kafka.bootstrap-servers=${KAFKA_BROKERS:localhost:29092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# TPS topic + interval
kafka.topic=${KAFKA_TOPIC:tps-treinpositie}
tps.publish.interval-ms=${PUBLISH_INTERVAL_MS:2000}

# RITS topic + interval
kafka.topic.rits=${KAFKA_TOPIC_RITS:rits-infratoestand}
rits.publish.interval-ms=${RITS_PUBLISH_INTERVAL_MS:3000}
